name: MobSFScan

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  mobsfscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install mobsfscan
        run: pip install mobsfscan

      - name: Run mobsfscan and generate JSON + SARIF reports
        run: |
          mobsfscan --json . > mobsfscan-report.json || true
          mobsfscan --sarif . > mobsfscan-results.sarif || true

      - name: Upload JSON report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-json-report
          path: mobsfscan-report.json

      - name: Upload SARIF report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: mobsfscan-results.sarif
