name: MobSFScan

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  mobsfscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install mobsfscan
        run: |
          pip install mobsfscan

      - name: Run mobsfscan and generate report
        run: |
          mobsfscan --json . > mobsfscan-report.json || true

      - name: Upload mobsfscan report
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-report
          path: mobsfscan-report.json
