name: MobSFScan

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  mobsfscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run mobsfscan and generate SARIF report
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output mobsfscan-results.sarif || true'

      - name: Inspect SARIF report issue count
        run: |
          echo "Detected findings:"
          jq '.runs[0].results | length' mobsfscan-results.sarif

      - name: Upload SARIF report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: mobsfscan-results.sarif

      - name: Upload SARIF report (artifact for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: mobsfscan-sarif-debug
          path: mobsfscan-results.sarif
